version: "3.3"
services:
  piston:
    container_name: piston
    image: ghcr.io/engineer-man/piston
    ports:
      - 9000:2000
    volumes:
      - ./tmp/piston/packages:/piston/packages
    tmpfs:
      - /piston/jobs:exec,uid=1000,gid=1000,mode=711
      - /tmp:exec
  backend:
    build: backend
    command: nodemon ./server.ts
    ports:
      - 8000:3000
    environment:
      DB_URI: mongodb://root:example@mongo:27017
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - piston
      - mongo
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
