version: "3.3"
services:
  piston:
    container_name: piston
    image: ghcr.io/engineer-man/piston
    ports:
      - 9000:2000
    volumes:
      - ./tmp/piston/packages:/piston/packages
    tmpfs:
      - /piston/jobs:exec,uid=1000,gid=1000,mode=711
      - /tmp:exec
  api:
    build: api
    command: nodemon ./server.ts
    ports:
      - 3000:3000
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - piston
